# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comm_data',
            new_name='comm_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reg_data',
            new_name='reg_date',
        ),
    ]
