# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160420_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvoteList',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoteList',
            field=models.TextField(null=True),
        ),
    ]
