# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160422_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='was_downvoted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='was_upvoted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
