# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160424_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/%Y/%m/%d/'),
        ),
    ]
