# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='website/Funny_Explosion.jpg', upload_to='website/%Y/%m/%d/'),
        ),
    ]
