# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160427_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='notFound.png', upload_to=''),
        ),
    ]
