# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_title',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
