# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_comment_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_user_id', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=1000)),
                ('mess_date', models.DateTimeField(verbose_name='data da mensagem')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
    ]
