# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='was_read',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
