# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_comment_was_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
