# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_message_was_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_user_username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
