# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_message_sender_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poster_username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
