# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_comment_poster_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/noAvatar.png', upload_to='user/'),
        ),
    ]
