# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
