# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_post_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
