# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
