# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_post_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_listing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
