# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_user_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
