# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20160509_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=300),
        ),
    ]
